### PR TITLE
Drilldown

### PR DESCRIPTION
**Pull request by phiaseitz**

### CODE REVIEW

**Comment by phiaseitz** [comment]
This should be merged after #35, as this will require merge conflict resolution

**Comment by phiaseitz** [comment]
Also merge this after #39 to make sure that all the legend-y stuff works okay and doesn't overlap.

**Comment by ManickYoj** [comment]
After this you've merged master with this and are ready for this to be reviewed, can you add a comment here so that I know to review it?

**Comment by phiaseitz** [comment]
Absolutely! I'm working out some background/national average stuff that broke, but it should be done shortly.

**Comment by ManickYoj** [comment]
Re: National Average I think I fixed that nicely along with some style tweaks in the next PR.

**Comment by phiaseitz** [comment]
resolves #21. I'm not exactly sure how this happened, but as far as the pull request goes there's some code related to the map overlay stuff that snuck its way in here. 

Other than that it looks like everything is working, and I fixed a bug where we always used the first datum to do the drilldown. 

I'll continue working on my legend styling tomorrow. 

@ManickYoj: This pull request should be good to go!

**Comment by ManickYoj** [comment]
Hmm. I'm encountering at least one bug.

Occasionally, after opening both sidebars and changing the category sliders, zooming in will produce this effect
image

I'll look into it.

**Comment by ManickYoj** [comment]
Also, under the same conditions, the drilldown on mouseover does not appear. The color changes, but the small wedges do not appear. It looks like when changing the sliders, two console errors appear:

`Uncaught TypeError: Cannot read property 'parentNode' of undefined (js: 34)`
and 
`Uncaught TypeError: Cannot read property 'parentNode' of undefined (visualizer.js 198)`

I assume it is related.

**Comment by phiaseitz** [comment]
I believe I've figured out what the error is. On adjusting the settings, we call update map, which hadn't been fully fleshed out in this PR. I believe that this should be ready to go now.

**Comment by ctada** [comment]
Fairly minor, but something seems off with the breakdown for some of the metrics. Are these on another issue? 
1. National average for only Quality. 
   image
2. No white stroke for Comfort drilldown
   image

**Comment by ctada** [comment]
For the national average thing, I think it's just the start/end angle that's throwing me off. Could be fine.

**Comment by phiaseitz** [comment]
hmmm odd. I can certainly take a look at that. I'll make an issue for that, so that we can get the drill down merged in.

**Comment by ctada** [comment]
Trying some more hospitals, looks like both bugs are for the start/end angle issue #49 . Otherwise looks good to me.

**Pull request merged**
