### PR TITLE
Drilldown fixes

### PR DESCRIPTION
**Pull request by phiaseitz**
@ctada I think this should fix the issue, but I wasn't able to replicate the exact same thing on my end. Could you check if this fixes it?

### CODE REVIEW

**Comment by ctada** [comment]
Fixes it on my end! One bug we hadn't thought of: when a metric sector is small enough, the breakdown just shows the white strokes, so a viewer can't tell which bar is which. Not something I'd be concerned about now, but something to keep in mind. 
image

**Comment by phiaseitz** [comment]
Okay! If I have extra time, I'll take a look at that!.

**Comment by ctada** [comment]
This includes changes from my earlier PR... which you've now merged in. Good to go.

**Comment by phiaseitz** [comment]
Resolves #49

**Pull request merged**
